Rebuild vendor directory with latest glide.yaml

diff --git a/vendor/k8s.io/kubernetes/hooks/pre-commit b/vendor/k8s.io/kubernetes/hooks/pre-commit
--- a/vendor/k8s.io/kubernetes/hooks/pre-commit
+++ b/vendor/k8s.io/kubernetes/hooks/pre-commit
@@ -7,7 +7,7 @@ readonly green=$(tput bold; tput setaf 2)
 exit_code=0
 
 echo -ne "Checking that it builds... "
-if ! OUT=$("hack/build-go.sh" 2>&1); then
+if ! OUT=$(make 2>&1); then
   echo
   echo "${red}${OUT}"
   exit_code=1
@@ -29,7 +29,7 @@ if [[ "${#files[@]}" -ne 0 ]]; then
   fi
   echo "${reset}"
 
-  echo -ne "Check if Godep licesnses are up to date..."
+  echo -ne "Check if Godep licenses are up to date..."
   if ! OUT=$("hack/verify-godep-licenses.sh" 2>&1); then
     echo
     echo "${red}${OUT}"
@@ -53,8 +53,8 @@ done
 
 if [[ "${#files_need_gofmt[@]}" -ne 0 ]]; then
   echo "${red}ERROR!"
-  echo "Some files have not been gofmt'd.  To fix these errors, "
-  echo "cut and paste the following:"
+  echo "Some files have not been gofmt'd. To fix these errors, "
+  echo "copy and paste the following:"
   echo "  gofmt -s -w ${files_need_gofmt[@]}"
   exit_code=1
 else
@@ -88,7 +88,7 @@ echo -ne "Checking for problems with flag names... "
 invalid_flag_lines=$(hack/verify-flags-underscore.py "${files[@]}")
 if [[ "${invalid_flag_lines:-}" != "" ]]; then
   echo "${red}ERROR!"
-  echo "There appear to be problems with the following"
+  echo "There appear to be problems with the following:"
   for line in "${invalid_flag_lines[@]}"; do
     echo "  ${line}"
   done
@@ -152,6 +152,30 @@ if ! hack/verify-swagger-spec.sh > /dev/null; then
   echo "Swagger spec needs to be updated."
   echo "To regenerate the spec, run:"
   echo "  hack/update-swagger-spec.sh"
+  exit_code=1
+else
+  echo "${green}OK"
+fi
+echo "${reset}"
+
+echo -ne "Checking for openapi spec that need updating... "
+if ! hack/verify-openapi-spec.sh > /dev/null; then
+  echo "${red}ERROR!"
+  echo "Openapi spec needs to be updated."
+  echo "To regenerate the spec, run:"
+  echo "  hack/update-openapi-spec.sh"
+  exit_code=1
+else
+  echo "${green}OK"
+fi
+echo "${reset}"
+
+echo -ne "Checking for federation openapi spec that need updating... "
+if ! hack/verify-federation-openapi-spec.sh > /dev/null; then
+  echo "${red}ERROR!"
+  echo "Federation OpenAPI spec needs to be updated."
+  echo "To regenerate the spec, run:"
+  echo "  hack/update-federation-openapi-spec.sh"
   exit_code=1
 else
   echo "${green}OK"
